### ISSUE TITLE
FECHAR Alterar design da página de edição do apontamento (ver imagem)

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#13]
![image](https://user-images.githubusercontent.com/36964153/36939167-6d6df0ca-1f0b-11e8-97da-d0abf6ef34a9.png)
![image](https://user-images.githubusercontent.com/36964153/36939355-16c74b92-1f0e-11e8-9490-1abed5fe6f23.png)

**Comment by paasetti** [comment]
Colocar um campo de links externos abaixo do campo de edição do apontamento. Pode ser que um apontamento tenha vários links externos ou nenhum - este campo pode ficar em branco

**Comment by Setti7** [comment]
Por que colocar um campo desse? Já da pra colocar link no corpo do texto.

**Comment by paasetti** [comment]
Tem razão, tinha esquecido do editor html. Ficou excelente do jeito que você fez. Só coloca embaixo de tudo o Campo Data de Edição

**Comment by Setti7** [comment]
Vc pode clicar em close tbm
