### ISSUE TITLE
Criar uma pagina de rosto para o site

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#14]
Mostrar Lista com titulo do apontamento; 180 primeiros caracteres do apontamento; EM ORDEM CRONOLÓGICA mostrando do ultimo editado ao com a editação mais antiga

colocar paginação em baixo 
menu igual ao site inteiro

**Comment by Setti7** [comment]
To pensando em fazer assim: na página inicial mostrar todos os livros, dai quando vc clica em um livro voce é redirecionado pra uma outra página com todos os apontamentos e etc daquele livro.

**Comment by paasetti** [comment]
Acho que você ja fez pelo que disse no whats. Mostra para mim.

**Comment by paasetti** [comment]
Eu acho legal. Eu dei a sugestão de home Page porque achava que o site
seria assim, só com as páginas administrativas. Não sabia que você estava
planejando um frontend.
Talvez seja melhor resolver tudo da parte administrativa antes de partir
pro frontend

Att.
Paulo André

Em 5 de mar de 2018 02:13, "André Setti" <notifications@github.com>
escreveu:

To pensando em fazer assim: na página inicial mostrar todos os livros, dai
quando vc clica em um livro voce é redirecionado pra uma outra página com
todos os apontamentos e etc daquele livro.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Setti7/Patest/issues/14#issuecomment-370311764>, or mute
the thread

**Comment by paasetti** [comment]
Eu acho legal. Eu dei a sugestão de home Page porque achava que o site seria assim, só com as páginas administrativas. Não sabia que você estava planejando um frontend.
Talvez seja melhor resolver tudo da parte administrativa antes de partir pro frontend
