### ISSUE TITLE
Criar sub menu exclusivo para a página que lista autores e a que lista livros

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#15]
Criar um menu com abc|def|ghi .... de modo que se clicar em abc a página recarrega com todos os autores cujo sobrenome comece com uma das letras do menu (abc lista todos os autores comecem com a, b, ou c em ordem alfabetica)

Baixa prioridade

**Comment by Setti7** [comment]
Quer isso ainda ou a barra de pesquisa já ta boa?

**Comment by paasetti** [comment]
Ta boa. não precisa fazer isto. Eu fazer js, mas ficou bom que acho que não vou fazer mais

**Comment by Setti7** [comment]
Eu achar legal, porem eu nao fazer.

**Comment by paasetti** [comment]
Apaga está. Ficou sem sentido

Att.
Paulo André

Em 11 de mar de 2018 23:57, "André Setti" <notifications@github.com>
escreveu:
