### ISSUE TITLE
Campo de caixa de seleção para Autor e Livro

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#24]
Este tipo de campo obriga você rodar por todas as opções até encontrar o nome desejado.
No access havia uma outra opção de funcionamento para uma caixa de seleção como esta: você podia digitar o nome do autor e ela apresentava as opções em que o digitado era igual ao banco de dados.
Por exemplo, se você digitava a Letra C, aparecia todos os que nome começam com C; se digitasse CE, aparecia todos os que tinham o nome iniciado pela sequencia CE, elimina todos cujos nomes iniciavam com CA, CI, CO, CU e todas as outras combinações possíveis diferentes de CE.
Isto iria ajudar quando a base de dados tiver muitos autores e livros. Eu estimo ter uns 2000 livros impressos e muito mais em epub. Provavelmente já teve ter um tipo de campo nesta linguagem que você está usando que resolve este problema, da forma que eu falei ou de outra forma qualquer. 
O Campo genero, não precisa ser alterado, não existirão muitos.
![image](https://user-images.githubusercontent.com/36964153/36945731-1110ac7e-1f91-11e8-81eb-555c4da7a792.png)

**Comment by Setti7** [comment]
Testa no site, acabei de adicionar "André Setti" e "Vitor Setti" e se vc digital "S" ele pula pra mim e se vc apertar dnv vai pro vitor? nao é o suficiente?

**Comment by paasetti** [comment]
sim
