### ISSUE TITLE
permitir que o campo NOME fique vazio

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#27]

**Comment by Setti7** [comment]
Você ainda quer isso? Ia dar um trabalhão porque eu ia ter q mudar a data structure, mas se vc quiser eu faço pq tem coisa pra aprender fazendo isso

**Comment by paasetti** [comment]
Nao precisa. A ideia que voce deu resolveu

**Comment by paasetti** [comment]
Já respondi no github. Não precié
a

Att.
Paulo André

Em 11 de mar de 2018 21:08, "André Setti" <notifications@github.com>
escreveu:
