### ISSUE TITLE
Idéias para o site: pagina de tags

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#29]
Será que dava para fazer quando uma página com as tags listadas em ordem alfabéticas e, quando eu clicasse sobre uma delas, fosse para outra página que listasse todos os apontamentos com aquela tag. Pode ser só o começo dos apontamentos, as 180 primeiras letras como você já fez.

**Comment by Setti7** [comment]
Vc ainda quer isso ou a função de busca já é o suficiente?

**Comment by paasetti** [comment]
Não precisa disto. Pode fechar esta tarefa
