### ISSUE TITLE
Adiconar tags aos apontamentos

### ISSUE THREAD

**Issue by Setti7** [Setti7/Patest#3]

**Comment by paasetti** [comment]
óculos, amadurecimento pessoal, descrição personagem, ação personagem, resenha, vestir-se
Um único apontamento deve ter no mínimo 5 tags, alguns talvez, dezenas

**Comment by paasetti** [comment]
Você conhece as tags cloud? è uma sugestão para apresentar as tags.

Fica assim
![image](https://user-images.githubusercontent.com/36964153/36946047-a2473de4-1f95-11e8-8141-ea5081703238.png)
quando mais a tag for usada maior é a letra dela. 


Aqui tem um exemplo do codigo que usam no wordpress, mas é php [](https://codex.wordpress.org/Function_Reference/wp_tag_cloud). Deve ter codigo semelhantes na linguagem em que você usa.

**Comment by Setti7** [comment]
https://github.com/alex/django-taggit
