### ISSUE TITLE
http://setti7.pythonanywhere.com/catalog/autores/18

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#33]
```
trocar a linha 95  
<h1 class="display-4 font-italic">Sade, Marquês de</h1> 
por esta: 
<h2>class="display-4 font-italic">Sade, Marquês de</h2>`

```
```
Trocar a linha 97: <p class="lead my-3">1 livro no registro.</p>
por esta: 

//* Ajusta o tamanho da fonte -3 ou -4 pt em <font size="-2">
<p class="lead my-3"><font size="-2">1 livro no registro.</font> Vivo entre: <font size="-2"><1740 - 1814</font></p>

apagar a linha 103: <p class="lead my-3">Nascimento/Morte:</br><br>1740 - 1814</p>

```
# Ja arrumei as tags de html estvam abertas para o editor não interpretar no navegador. Não sabia como inserir codigo aqui. Agora já Aprendi

**Comment by paasetti** [comment]
trocar a linha 95  h1 class="display-4 font-italic">Sade, Marquês de</h1> 
por esta:  h2 class="display-4 font-italic">Sade, Marquês de</h2>

Trocar a linha 97: <p class="lead my-3">1 livro no registro.</p>
por esta: p class="lead my-3">1 livro no registro. Nascimento/Morte: 1740 - 1814</p>

apagar a linha 103: p class="lead my-3">Nascimento/Morte: br>1740 - 1814</p>

Se vc fizer isto o cabeçalho descritivo vai fica estrito na altura, mas facil de consultar a pag. Na realidade só tirei um paragrafo e um /br>

**Comment by paasetti** [comment]
Logo abaixo tem estas linhas

h4 class="font-italic">Número de apontamentos:</h4>
--
  |  
  | <p class="mb-0">1</p>
  |  
  |  
  |  
  | <h4 class="font-italic">Cidade:</h4>
  | <p class="mb-0">São Paulo</p>
  |  
  |  
  |  
  | <h4 class="font-italic">Editora:</h4>
  | <p class="mb-0">Iluminuras</p>
  |  
  |  
  |  
  | <h4 class="font-italic">Ano de publicação:</h4>
  | <p class="mb-0">1999</p>
  |  
  |  
  |  
  | <h4 class="font-italic">Gênero:</h4>
  | <p class="mb-0">Romance</p>

Poderia ficar assim:
h4 class="font-italic">Número de apontamentos: 1</h4> numero de apontamento na mesma linha
<h4 class="font-italic">Publicado por: Cidade: Nome da Editora, ano</h4> coloquei cidade: nome da editora e ano na mesma linha
<h4 class="font-italic">Gênero: Romance</h4> Uma linha só tag Genero: Romance.

**Comment by Setti7** [comment]
Não deu certo. Se eu fizer só isso a fonte fica toda aquela grande e dai fica mt dificil de ler. Dps eu vejo como fazer isso certinho.

**Comment by paasetti** [comment]
Ok

Att.
Paulo André

Em 12 de mar de 2018 00:18, "André Setti" <notifications@github.com>
escreveu:
