### ISSUE TITLE
Sugestão de novo icone para menu

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#35]
Escolha o que você gostar mais. Eu gosto de todos Já deixei os fundos transparente. Não vai ficar o quadradinho branco.
![apontamento 1](https://user-images.githubusercontent.com/36964153/37284058-f05e04ce-25d8-11e8-9815-912d594dce28.png)
![apontamento2](https://user-images.githubusercontent.com/36964153/37284062-f421d126-25d8-11e8-885a-8faac5fd7559.png)
![apontamento3](https://user-images.githubusercontent.com/36964153/37284068-f78b91c6-25d8-11e8-80ea-f0b67e9d5800.png)
![apontamento3-64x64](https://user-images.githubusercontent.com/36964153/37284092-09012240-25d9-11e8-947d-0bd1c726862c.png)
![apontamento6](https://user-images.githubusercontent.com/36964153/37284142-34f6d700-25d9-11e8-93a2-bd3a8889de87.png)
![apontamento6-64](https://user-images.githubusercontent.com/36964153/37284159-41fbd82e-25d9-11e8-85a6-40e206983728.png)
![apontamento164x64](https://user-images.githubusercontent.com/36964153/37284164-45d1d25a-25d9-11e8-9ecb-ce2c68c89f1c.png)

![apontamento4](https://user-images.githubusercontent.com/36964153/37284099-0e3f11e0-25d9-11e8-9811-9302658aafba.png)
![apontamento4-64](https://user-images.githubusercontent.com/36964153/37284101-12f012e8-25d9-11e8-96f9-7cd0c888de6e.png)
![apontamento5](https://user-images.githubusercontent.com/36964153/37284105-19c33b0e-25d9-11e8-9810-56634881fa4f.png)
![apontamento5-64](https://user-images.githubusercontent.com/36964153/37284112-20f1ec22-25d9-11e8-84cf-0b39edc5cf66.png)
![apontamento264x64](https://user-images.githubusercontent.com/36964153/37284187-55b6e278-25d9-11e8-8d1e-d257339e71d5.png)

**Comment by Setti7** [comment]
Algum deles tem direito autoral? Pq como o site a público eu preciso por creditos se tiver

**Comment by paasetti** [comment]
Não. Não tem. Peguei os que são distribuidos gratis. Não precisa citar
direito autoral.

2018-03-12 21:58 GMT-03:00, André Setti <notifications@github.com>:
> Algum deles tem direito autoral? Pq como o site a público eu preciso por
> creditos se tiver
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Setti7/Patest/issues/35#issuecomment-372510850


-- 


*-------*

*Atenciosamente,*

*Paulo *
