### ISSUE TITLE
Como usar site on line e offline ao mesmo tempo

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#36]
Tem jeito de você me mandar uma versão de como está agora o site.
Tive a seguinte ideia: Vou alterar todas as paginas do site no meu computador e tirar dos links de edição ou para area administrativa. No meu computar vai ficar apenas uma versão de consulta. Eu vou poder ler os conteudos, mas não modifica-los e a acrescenta-lo. Edição só na versão online. 
Ai você faz um aplicativo que manda pra meu email, toda as sexta-feiras, o banco de dados para eu atualizar o site de consultas no meu computador com as novidades que coloquei online.

Vou usar css: Display:none!important.

**Comment by Setti7** [comment]
Posso colocar no site online um botao de download do banco de dados

**Comment by paasetti** [comment]
Blz. Melhor ainda. Quando puder manda uma nova versão do site no github para eu instalar no meu computador
