### ISSUE TITLE
Mudar style pra icy orange

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#48]
[](veja as instruções nesta página https://docs.ckeditor.com/ckeditor5/latest/features/text-alignment.html)

**Comment by Setti7** [comment]
Não é tão simples assim porque a implementação do ckeditor que eu usei foi diferente. Não consegui mudar nada.

**Comment by Setti7** [comment]
https://ckeditor.com/cke4/builder

https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic
