### ISSUE TITLE
Caixa de pesquisa

### ISSUE THREAD

**Issue by paasetti** [Setti7/Patest#7]
No cabeçalho do site é preciso ter uma caixa de pesquisa (pode ser uma página a parte também) que retorno todas as linhas da tabela que contem o que quero buscar.

Por exemplo, eu digito romance, ele retorna

Titulo do apontamento   - caso tenha a palavra nos campos titulo do apontamento ou apontamento
Nome e Sobrenome do Autor - no caso do se chamar Orivaldo Romance
Gênero: Romance

**Comment by Setti7** [comment]
https://django-haystack.readthedocs.io/en/master/
